//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiKey
    {
        public ApiKey()
        {
            this.ApiKeyEntities = new HashSet<ApiKeyEntity>();
        }
    
        public int Id { get; set; }
        public long ApiKeyId { get; set; }
        public string VCode { get; set; }
        public string KeyType { get; set; }
    
        public virtual ICollection<ApiKeyEntity> ApiKeyEntities { get; set; }
    }
}
