//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int Id { get; set; }
        public int InvTypes_TypeId { get; set; }
        public int Quantity { get; set; }
        public int ApiKeyEntity_Id { get; set; }
        public int UnaccountedQuantity { get; set; }
        public decimal LatestAverageCost { get; set; }
        public int ActualQuantity { get; set; }
        public decimal BrokerFees { get; set; }
        public decimal MaterialCost { get; set; }
        public int MarketQuantity { get; set; }
    
        public virtual ApiKeyEntity ApiKeyEntity { get; set; }
        public virtual InvType invType { get; set; }
    }
}
