//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchMaterial
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public int BatchId { get; set; }
        public int Quantity { get; set; }
        public decimal TotalCost { get; set; }
    
        public virtual InvType invType { get; set; }
        public virtual ProductionBatch ProductionBatch { get; set; }
    }
}
