//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FifoCost
    {
        public int Id { get; set; }
        public int BuyTransactionId { get; set; }
        public int SellTransactionId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Transaction BuyTransaction { get; set; }
        public virtual Transaction SellTransaction { get; set; }
    }
}
