//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvBlueprintType
    {
        public InvBlueprintType()
        {
            this.ProductionBatches = new HashSet<ProductionBatch>();
        }
    
        public int BlueprintTypeId { get; set; }
        public Nullable<int> ParentBlueprintTypeID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> ProductionTime { get; set; }
        public Nullable<short> TechLevel { get; set; }
        public Nullable<int> ResearchProductivityTime { get; set; }
        public Nullable<int> ResearchMaterialTime { get; set; }
        public Nullable<int> ResearchCopyTime { get; set; }
        public Nullable<int> ResearchTechTime { get; set; }
        public Nullable<int> ProductivityModifier { get; set; }
        public Nullable<short> MaterialModifier { get; set; }
        public Nullable<short> WasteFactor { get; set; }
        public Nullable<int> MaxProductionLimit { get; set; }
    
        public virtual InvType BlueprintInvType { get; set; }
        public virtual ICollection<ProductionBatch> ProductionBatches { get; set; }
        public virtual InvType ProductInvType { get; set; }
    }
}
