//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvGroup
    {
        public InvGroup()
        {
            this.InvTypes = new HashSet<InvType>();
        }
    
        public int GroupId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public Nullable<int> IconId { get; set; }
        public Nullable<bool> UseBasePrice { get; set; }
        public Nullable<bool> AllowManufacture { get; set; }
        public Nullable<bool> AllowRecycler { get; set; }
        public Nullable<bool> Anchored { get; set; }
        public Nullable<bool> Anchorable { get; set; }
        public Nullable<bool> FittableNonSingleton { get; set; }
        public Nullable<bool> Published { get; set; }
    
        public virtual ICollection<InvType> InvTypes { get; set; }
    }
}
