//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMarketGroup
    {
        public InvMarketGroup()
        {
            this.InvTypes = new HashSet<InvType>();
            this.ChildGroups = new HashSet<InvMarketGroup>();
        }
    
        public int MarketGroupId { get; set; }
        public Nullable<int> ParentGroupId { get; set; }
        public string MarketGroupName { get; set; }
        public string Description { get; set; }
        public Nullable<int> IconId { get; set; }
        public Nullable<bool> HasTypes { get; set; }
    
        public virtual ICollection<InvType> InvTypes { get; set; }
        public virtual ICollection<InvMarketGroup> ChildGroups { get; set; }
        public virtual InvMarketGroup ParentGroup { get; set; }
    }
}
