//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvType
    {
        public InvType()
        {
            this.Orders = new HashSet<Order>();
            this.Transactions = new HashSet<Transaction>();
            this.ItemCosts = new HashSet<ItemCost>();
        }
    
        public int TypeId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
        public Nullable<double> Mass { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Capacity { get; set; }
        public Nullable<int> PortionSize { get; set; }
        public Nullable<byte> RaceId { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<int> MarketGroupId { get; set; }
        public Nullable<double> ChanceOfDuplicating { get; set; }
    
        public virtual InvMarketGroup InvMarketGroup { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual InvGroup InvGroup { get; set; }
        public virtual ICollection<ItemCost> ItemCosts { get; set; }
    }
}
