//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public long RefId { get; set; }
        public string OwnerName { get; set; }
        public long OwnerId { get; set; }
        public string ParticipantName { get; set; }
        public long ParticipantId { get; set; }
        public string ArgumentName { get; set; }
        public long ArgumentId { get; set; }
        public decimal Amount { get; set; }
        public decimal BalanceAfter { get; set; }
        public string Reason { get; set; }
        public string TaxReceiverId { get; set; }
        public string TaxAmount { get; set; }
        public Nullable<int> ApiKeyEntity_Id { get; set; }
        public int OwnerTypeId { get; set; }
        public int ParticipantTypeId { get; set; }
        public int RefTypeId { get; set; }
    
        public virtual ApiKeyEntity ApiKeyEntity { get; set; }
        public virtual InvType OwnerType { get; set; }
        public virtual InvType ParticipantType { get; set; }
        public virtual RefType RefType { get; set; }
    }
}
