//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketOrder
    {
        public int Id { get; set; }
        public long OrderId { get; set; }
        public int ApiKeyEntityId { get; set; }
        public int StationId { get; set; }
        public int VolumeEntered { get; set; }
        public int VolumeRemaining { get; set; }
        public int MinVolume { get; set; }
        public OrderState OrderState { get; set; }
        public int TypeId { get; set; }
        public int Range { get; set; }
        public int AccountKey { get; set; }
        public int Duration { get; set; }
        public decimal Escrow { get; set; }
        public decimal Price { get; set; }
        public bool Bid { get; set; }
        public System.DateTime Issued { get; set; }
    
        public virtual StaStation Station { get; set; }
        public virtual InvType InvType { get; set; }
        public virtual ApiKeyEntity ApiKeyEntity { get; set; }
    }
}
