//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    
    public enum OrderState : int
    {
        Open = 0,
        Closed = 1,
        Expired = 2,
        Cancelled = 3,
        Pending = 4,
        CharacterDeleted = 5
    }
}
