//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZet.EveProfiteer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionBatch
    {
        public ProductionBatch()
        {
            this.BatchMaterials = new HashSet<BatchMaterial>();
        }
    
        public int Id { get; set; }
        public int ProductTypeId { get; set; }
        public int BlueprintTypeId { get; set; }
        public int ProductionQuantity { get; set; }
        public int QuantityLeft { get; set; }
        public System.DateTime Date { get; set; }
        public decimal OtherCost { get; set; }
        public decimal TotalSales { get; set; }
        public int BlueprintME { get; set; }
        public int CharacterME { get; set; }
    
        public virtual ICollection<BatchMaterial> BatchMaterials { get; set; }
        public virtual InvType InvType { get; set; }
        public virtual InvBlueprintType InvBlueprintType { get; set; }
    }
}
